name: Package and Publish to GitHub Packages

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*' # Trigger only on tags like v1.0.0
  pull_request:
    branches: [ main ]

#The permissions: section defines the permissions granted to the GITHUB_TOKEN for this workflow or job.
#packages: write explicitly allows the GITHUB_TOKEN to write (upload) packages to the GitHub Packages registry associated with your repository.
#contents: read is typically needed for the actions/checkout step to access your repository's code.
permissions:
  packages: write
  contents: read # This is usually a good idea to keep for checkout


jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src/FileWriter # Adjust to your project path

    steps:

    - name: Echo GitHub Ref
      run: echo "The GitHub Ref is" ${{ github.ref }}

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x' # Or your desired .NET SDK version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Pack NuGet package
      run: dotnet pack --configuration Release --output .

    - name: List files before push
      if: startsWith(github.ref, 'refs/tags/v')
      run: ls -l *.nupkg

    - name: Configure Git
      run: dotnet nuget add source --username seanr89 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/seanr89/index.json"   

    - name: Push to GitHub Packages
      if: startsWith(github.ref, 'refs/tags/v') # Only run on tagged commits
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: dotnet nuget push "*.nupkg" --source "github" --api-key "${{ secrets.GITHUB_TOKEN }}"
